"""initial migration

Revision ID: e7f4c48e49a4
Revises: 
Create Date: 2025-07-08 01:17:07.563043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f4c48e49a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('sub_county', sa.String(length=100), nullable=True),
    sa.Column('uic', sa.String(length=20), nullable=True),
    sa.Column('knec', sa.String(length=20), nullable=True),
    sa.Column('school_name', sa.String(length=200), nullable=True),
    sa.Column('cluster', sa.String(length=10), nullable=True),
    sa.Column('school_type', sa.String(length=50), nullable=True),
    sa.Column('disability_type', sa.String(length=50), nullable=True),
    sa.Column('accommodation_type', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schools')
    # ### end Alembic commands ###
